version: '3'
services:
  kq:
    image: richardchien/cqhttp
    container_name: kq
    ports:
      - "9000:9000"
      - "5700:5700"
    volumes:
      - ./data/coolq-data:/home/user/coolq
    environment:
      VNC_PASSWD: 12345678
      COOLQ_ACCOUNT: 1278716328
      CQHTTP_POST_URL: http://host.docker.internal:8080/msg
      CQHTTP_SERVE_DATA_FILES: 'yes'