version: '3'
services:
  kq:
    image: richardchien/cqhttp
    container_name: kq
    ports:
      - "9000:9000"
      - "5700:5700"
    volumes:
      - ./data/coolq-data:/home/user/coolq
    environment:
      VNC_PASSWD: toplevel715
      COOLQ_ACCOUNT: 1824018300
      CQHTTP_POST_URL: http://bot:8080/msg
      CQHTTP_SERVE_DATA_FILES: 'yes'
    external_links:
      - bot
    networks:
      - net
networks:
  net:
    external: true